config/routes.rb
Rails.application.routes.draw do
  get 'search' => 'searches#search'
  get "search_tag"=>"books#search_tag"
  get 'relationships/followings'
  get 'relationships/followers'
  # For details on the DSL available within this file, see http://guides.rubyonrails.org/routing.html
  devise_for :users
  root :to =>"homes#top"
  get "home/about"=>"homes#about"
  resources :books, only: [:index,:show,:edit,:create,:destroy,:update] do
    resources :book_comments, only: [:create, :destroy]
    resource :favorites, only: [:create, :destroy]
  end
  resources :users, only: [:index,:show,:edit,:update] do
    resource :relationships, only: [:create, :destroy]
    get "followings" => "relationships#followings", as: "followings"
    get "followers" => "relationships#followers", as: "followers"
  end

  resources :messages, only: [:create]
  resources :rooms, only: [:create, :show, :index]

  resources :groups do
    get "join" => "groups#join"
    get "new/mail" => "groups#new_mail"
    get "send/mail" => "groups#send_mail"
  end

  # For details on the DSL available within this file, see https://guides.rubyonrails.org/routing.html
end

app/models/book.rb
class Book < ApplicationRecord
  belongs_to :user
  has_many :favorites, dependent: :destroy
  #includesで呼び出すときのカラム
  has_many :favorited_users, through: :favorites, source: :user
  #一週間の間のいいねを呼び出すカラム
  has_many :week_favorites, -> { where(created_at: ((Time.current.at_end_of_day - 6.day).at_beginning_of_day)..(Time.current.at_end_of_day)) }, class_name: 'Favorite'
  has_many :book_comments, dependent: :destroy

  has_many :view_counts, dependent: :destroy

  has_many :book_tags,dependent: :destroy
  has_many :tags,through: :book_tags

  validates :title,presence:true
  validates :body,presence:true,length:{maximum:200}

  scope :latest, -> {order(created_at: :desc)}
  scope :rate_count, -> {order(rate: :desc)}

  def favorited_by?(user)
    favorites.exists?(user_id: user.id)
  end

  def self.search(search, word)
    if search == "forward_match"
      @book = Book.where("title LIKE?","#{word}%")
    elsif search == "backward_match"
      @book = Book.where("title LIKE?","%#{word}")
    elsif search == "perfect_match"
      @book = Book.where(title: "#{word}")
    elsif search == "partial_match"
      @book = Book.where("title LIKE?","%#{word}%")
    else
      @book = Book.all
    end
  end

  def save_tag(sent_tags)
  # タグが存在していれば、タグの名前を配列として全て取得
    current_tags = self.tags.pluck(:name) unless self.tags.nil?
    # 現在取得したタグから送られてきたタグを除いてoldtagとする
    old_tags = current_tags - sent_tags
    # 送信されてきたタグから現在存在するタグを除いたタグをnewとする
    new_tags = sent_tags - current_tags

    # 古いタグを消す
    old_tags.each do |old|
      self.tags.delete Tag.find_by(name: old)
    end

    # 新しいタグを保存
    new_tags.each do |new|
      new_book_tag = Tag.find_or_create_by(name: new)
      self.tags << new_book_tag
   end
  end

end

app/controllers/books_controller.rb
class BooksController < ApplicationController

before_action :correct_user, only: [:edit, :update]

  def show
    @book = Book.find(params[:id])
    @books = Book.new
    @user = @book.user
    @book_tags = @book.tags
    @book_comment = BookComment.new
    unless ViewCount.find_by(user_id: current_user.id, book_id: @book.id)
      current_user.view_counts.create(book_id: @book.id)
    end

    #DM機能の作成
    #自分のエントリー情報を抽出
    @currentUserEntry = Entry.where(user_id: current_user.id)
    #見てるページのユーザーのエントリー情報を抽出
    @userEntry = Entry.where(user_id: @user.id)
    #見てるページのユーザーと自分のユーザーがおんなじかどうか
    if @user.id == current_user.id
    else
    #自分の持ってるエントリー情報と見てるページのユーザーのエントリー情報をすべて抽出する
      @currentUserEntry.each do |cu|
        @userEntry.each do |u|
    #自分の持ってるroom_idと見てるページのユーザーの持ってるroom_idの中に同じroom_idがあるかどうか
          if cu.room_id == u.room_id then
    #roomはあるよと定義しroom_idをインスタンス変数で渡す
            @isRoom = true
            @roomId = cu.room_id
          end
        end
      end
    #roomがない場合
      if @isRoom
      else
    #新しいインスタンスを制作する
        @room = Room.new
        @entry = Entry.new
      end
    end

  end

  def index
    @book = Book.new
    @tag_list = Tag.all.sort_by {|x| x.books.count}.reverse
    #一週間のいいねの多い順
    #今日の終わり
    to = Time.current.at_end_of_day
    #一週間前
    from = (to - 6.day).at_beginning_of_day
    if params[:latest]
      @books = Book.latest
      #render :sort_index
    elsif params[:rate_count]
      @books = Book.rate_count
      #render :sort_index
    else
      #favoriteとuserを取り出しておいて、一週間前から今日の終わりまででのいいね数でソートする
      @books = Book.includes(:favorited_users).
      sort_by {|x|
        x.favorites.where(created_at: from...to).size
      }.reverse
    end
  end

  def create
    @book = Book.new(book_params)
    @book.user_id = current_user.id
    tag_list=params[:book][:name].split(',')
    if @book.save
      @book.save_tag(tag_list)
      redirect_to book_path(@book.id), notice: "You have created book successfully."
    else
      @books = Book.all
      render 'index'
    end
  end

  def edit
    @edit = true
    @book = Book.find(params[:id])
  end

  def update
    @book = Book.find(params[:id])
    tag_list=params[:book][:name].split(',')
    if @book.update(book_params)
      @book.save_tag(tag_list)
      redirect_to book_path(@book), notice: "You have updated book successfully."
    else
      render "edit"
    end
  end

  def destroy
    @book = Book.find(params[:id])
    @book.destroy
    redirect_to books_path
  end

  def search_tag
    #検索結果画面でもタグ一覧表示
    @tag_list=Tag.all.sort_by {|x| x.books.count}.reverse
    #検索されたタグを受け取る
    @tag=Tag.find(params[:tag_id])
    #検索されたタグに紐づく投稿を表示

    #一週間のいいねの多い順
    #今日の終わり
    to = Time.current.at_end_of_day
    #一週間前
    from = (to - 6.day).at_beginning_of_day

    @books=@tag.books.includes(:favorited_users).
      sort_by {|x|
        x.favorites.where(created_at: from...to).size
      }.reverse
  end

  private

  def book_params
    params.require(:book).permit(:title, :body, :rate)
  end

  def correct_user
    @book = Book.find(params[:id])
    @user = @book.user
    redirect_to(books_path) unless @user == current_user
  end

end

app/helpers/books_helper.rb
module BooksHelper
end

app/views/books/_form.html.erb
<%= form_with model:book,local:true do |f| %>
  <div class="form-group">
    <%= f.label :title %>
    <%= f.text_field :title, class: 'form-control book_title' %>
  </div>
  <div class="form-group">
    <%= f.label :opinion %>
    <%= f.text_area :body, class: 'form-control book_body' %>
  </div>

  <div class="field">
    <%= f.label"タグ (,で区切ると複数タグ登録できます)" %>
    <%= f.text_field :name,value: book.tags.pluck(:name).join(','),class:"form-control" %>
  </div>

  <% if edit == true %>
  <% else %>
    <% if book.id === nil %>
      <div class="form-group" id="star">
        <%= f.label :rate %>
        <%= f.hidden_field :rate, id: :review_star, class:'form-control' %>
      </div>

      <script>
      $(document).on('turbolinks:load', function() {
        $('#star').empty();
        $('#star').raty({
          size     : 36,
          starOff:  '<%= asset_path('star-off.png') %>',
          starOn : '<%= asset_path('star-on.png') %>',
          starHalf: '<%= asset_path('star-half.png') %>',
          scoreName: 'book[rate]',
          half: true,
        });
      })
      </script>
    <% else %>
      <%= render "static_rate", book: book %>
    <% end %>
  <% end %>


  <div class="form-group">
    <%= f.submit class: 'btn btn-success' %>
  </div>
<% end %>

app/views/books/_index.html.erb
<table class='table table-hover table-inverse'>
  <thead>
    <tr>
      <th></th>
      <th>Title</th>
      <th>Opinion</th>
      <th>Tag</th>
      <th colspan="3"></th>
    </tr>
  </thead>
  <tbody>
    <% books.each do |book| %>
      <tr>
        <td><%= link_to(book.user) do %>
          <%= image_tag book.user.get_profile_image, size:'50x50' %>
          <% end %>
        </td>
        <td><%= link_to book.title,book, class: "book_#{book.id}" %></td>
        <td><%= book.body %></td>
        <td>
          <% book.tags.each do |tag| %>
            <%= tag.name %><br>
          <% end %>
        </td>
        <td id="favorite_buttons_<%= book.id %>">
          <%= render 'favorites/favorite', book: book %>
        </td>

        <td><%= render 'book_comments/count', book: book %></td>
        <td><%= render "books/rate", book: book %></td>
        <td><%= render "view_count/count", book: book %></td>
      </tr>
    <% end %>
  </tbody>
</table>

app/views/books/_rate.html.erb
<div id="rate_<%= book.id %>" class="form-group"></div>
<script>
$(document).on('turbolinks:load', function() {
  $('#rate_<%= book.id %>').empty();
  $('#rate_<%= book.id %>').raty({
    size: 20,
    starOff:  '<%= asset_path('star-off.png') %>',
    starOn : '<%= asset_path('star-on.png') %>',
    starHalf: '<%= asset_path('star-half.png') %>',
    half: true,
    readOnly: true,
    score: <%= book.rate %>,
  });
});
</script>

app/views/books/edit.html.erb
<div class='container'>
  <%= render 'layouts/errors', obj: @book %>
  <div class='row'>
    <div class="col-sm-12 col-md-8 col-lg-5 px-5 px-sm-0 mx-auto">
  		<h1>Editing Book</h1>
  		<%= render 'form', book: @book, edit: @edit %>
  		<%= link_to 'Show', @book, class: "book_#{@book.id}" %> |
  		<%= link_to 'Back', books_path, class: "back" %>
  </div>
</div>

app/views/books/index.html.erb
<div class='container px-5 px-sm-0'>
<%= render 'layouts/errors', obj: @book %>
  <div class='row'>
    <div class='col-md-3'>
      <h2>User info</h2>
      <%= render 'users/info', user: current_user %>
      <h2 class="mt-3">New book</h2>
      <%= render 'form', book: @book, edit: @edit %>
    </div>
    <div class='col-md-8 offset-md-1'>
      <h2>Books</h2>
      <p>
        <% @tag_list.each do |list| %>
          <%= link_to list.name,search_tag_path(tag_id: list.id) %>
          <%= "(#{list.books.count})" %>
        <% end %>
      </p>
      <p>
        <!-- link_to '新しい順', books_path(latest: "true"), remote:true -->
        <%= link_to '新しい順', books_path(latest: "true") %>
        |<!-- link_to '評価の高い順', books_path(rate_count: "true"), remote:true -->
        <%= link_to '評価の高い順', books_path(rate_count: "true") %>
      </p>
      <div id="sort_area">
        <%= render 'index', books: @books%>
      </div>
    </div>
  </div>
</div>

app/views/books/search_tag.html.erb
<% @tag_list.each do |list|%>
<%=link_to list.name,search_tag_path(tag_id: list.id) %>
<%="(#{list.books.count})" %><% end %>

<h2>タグが<%=@tag.name%>の投稿一覧</h2>

<table class="table table-hover table-inverse">
  <thead>
    <tr>
     <th></th>
     <th>Title</th>
     <th>Opinion</th>
     <th colspan="3"></th>
    </tr>
  </thead>


  <tbody>
     <% @books.each do |book| %>
     <tr>
      <td>
       <%= link_to(book.user) do %>
       <%= image_tag book.user.get_profile_image, size:'50x50' %>
       <% end %>
      </td>
      <td>
       <%= link_to book.title, book, class: "book_#{book.id}" %>
      </td>
      <td><%= book.body %></td>
     </tr>
     <% end %>
  </tbody>

app/views/books/show.html.erb
<div class='container'>
  <div class='row'>
    <div class='col-md-3'>
      <h2>User info</h2>
      <%= render 'users/info', user: @user, isRoom: @isRoom, roomId: @roomId, room: @room, entry: @entry %>
      <h2 class="mt-3">New book</h2>
      <%= render 'form', book: @books, edit: @edit %>
    </div>
    <div class='col-md-8 offset-md-1'>
  		<h2>Book detail</h2>
  		<table class='table'>
  		  <thead>
          <tr>
            <th></th>
            <th>Title</th>
            <th>Opinion</th>
            <th>Tag</th>
            <th colspan="3"></th>
          </tr>
        </thead>
  		  <tbody>
      		  <tr>
            <td>
              <%= link_to(@book.user) do %>
                <%= image_tag @book.user.get_profile_image, size:"50x50" %><br>
                <%= @book.user.name %>
              <% end %>
            </td>
            <td><%= link_to @book.title, @book %></td>
            <td><%= @book.body %></td>
            <td>
              <% @book_tags.each do |tag| %>
                <%= tag.name %> <br>
              <% end %>
            </td>
            <% if @book.user == current_user %>
              <td><%= link_to 'Edit', edit_book_path(@book), class: "btn btn-sm btn-success edit_book_#{@book.id}" %></td>
              <td><%= link_to 'Destroy', @book, method: :delete, data: { confirm: '本当に消しますか？' }, class: "btn btn-sm btn-danger destroy_book_#{@book.id}"%></td>
            <% end %>
            <td id="favorite_buttons_<%= @book.id %>">
              <%= render 'favorites/favorite', book: @book %>
            </td>


            <td id="comment_count"><%= render 'book_comments/count', book: @book %></td>
            <td><%= render "books/rate", book: @book %></td>
            <td><%= render "view_count/count", book: @book %></td>
            
          </tr>
        </tbody>
      </table>


        <table id="comments_area">
        <%= render 'book_comments/index', book: @book %>
        </table>


        <div class="new-comment">
          <%= render 'book_comments/form', book: @book, book_comment: @book_comment %>
        </div>


    </div>
  </div>
</div>

app/views/books/sort_index.js.erb
$("#sort_area").html("<%= j(render 'books/index', books: @books) %>");